server:
  port: 8888
spring:
  kafka:
    consumer:
      bootstrap-servers: http://localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.teramedica.kafakaex001web.model
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      group-id: poc-kafka-consumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      application-id: kafka9000-v0.1
      properties: # properties not explicitly handled by KafkaProperties.streams
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
    template:
      default-topic: poc-kafka
  data:
    mongodb:
      uri: mongodb://appuser:secret@127.0.0.1:27017/memory-game?authSource=admin